FROM node:16-alpine

WORKDIR /project/app
COPY ./client ./client

WORKDIR /project/app/client
RUN npm install
RUN npm run build

WORKDIR /project/app
COPY ./*.json ./
COPY ./src ./src
COPY ./.eslintrc.js ./
COPY ./.prettierrc ./
COPY ./tsconfig.build.json ./
COPY ./tsconfig.json ./
COPY ./nest-cli.json ./
COPY ./images ./images
COPY ./resumes ./resumes

RUN npm install
RUN npm run build

ENV NODE_ENV=production

CMD npm run start:prod