version: '3'

services:
  backend:
    image: backend:latest-prod
    network_mode: host
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    volumes:
      - ./.env:/project/app/.env
      - ./images:/project/app/images
      - ./resumes:/project/app/resumes
    ports:
      - "3001:3001"
